server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///E:/Project_Space/InternetBanking/Tradezy_config_server_git/tradezy
          search-paths: configuration
          default-label: main

application:
  name: config-server
